controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# routes.yaml
a-propos:
    path: /a-propos
    controller: 'App\Controller\AboutUsController::index'

accueil:
    path: /
    controller: 'App\Controller\PageController::index'

soins:
    path: /soins
    controller: 'App\Controller\CategoriesController::index'

soin_details:
    path: /nos-soins/{categoryId}  # Use the same parameter name as in the URL
    controller: 'App\Controller\SoinsController::category'
    requirements:
        categoryId: '\d+'

tarifs:
    path: /tarifs
    controller: 'App\Controller\OurPricesController::index'


category_list_services:
    path: /category/{id}/services
    controller: 'App\Controller\BookingServicesController::listServices'
    requirements:
        id: \d+
    defaults:
        controller: 'App\Controller\BookingServicesController::listServices'
        googleApiKey: 'AIzaSyAJOE5ji9Sz-bj7ksBG8kWV9BXc1y_wk7E' # Remplacez par votre clé API Google réelle

reset_password:
    path: '/reset-password/{token}'
    controller: App\Controller\PasswordResetController::reset
    methods: ['GET', 'POST']
